:sparkles:[Feat]: 아이템 목록 조회 구현
goormthon-Univ/2024_BEOTKKOTTHON_TEAM_25_BE pull request #44
Opened 2024-03-20 10:22 UTC by SIWON990327

# 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

# ❗️ 관련 이슈 링크
Close #42 

# 📌 개요
카테고리를 통해 아이템 목록을 조회하는 기능을 구현하였습니다
- 페이징은 구현하지 않았습니다

# 🔁 변경 사항
## 기능 1

# 👀 기타 더 이야기해볼 점

# ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-03-20 12:03 UTC, eomgerm requested changes

2024-03-20 12:03 UTC, eomgerm commented on src/main/java/com/goormthonuniv/ownearth/domain/enums/ItemCategory.java
> +  의류,
한글 말고 영어로 갑시다!

2024-03-20 12:03 UTC, eomgerm commented on src/main/java/com/goormthonuniv/ownearth/controller/ItemController.java
> +  @GetMapping("/item")
아이템 목록이니까 단수로 가면 안되죠! 그냥 `~/items` 이렇게 가야할 것 같아요!

2024-03-20 12:03 UTC, eomgerm commented on src/main/java/com/goormthonuniv/ownearth/dto/response/ItemResponseDto.java
> +  public static class ItemResponse {
이미 구매했는지도 보여주면 좋을 것 같아요

2024-03-21 00:41 UTC, eomgerm requested changes

2024-03-21 00:41 UTC, eomgerm commented on src/main/java/com/goormthonuniv/ownearth/controller/ItemController.java
> +  @GetMapping("/items")
저는 엔드포인트 자체가 `api/vi/items` 여야한다는 말이었어요!

2024-03-21 00:41 UTC, eomgerm commented on src/main/java/com/goormthonuniv/ownearth/converter/ItemConverter.java
> +            .anyMatch(memberItem -> memberItem.getMember().getId().equals(member.getId()));
여기 로직이 잘못된 것 같은데
`anyMatch(memberItem -> memberItem.getItem() == item)` 이렇게 가야하지 않나요?

2024-03-21 00:41 UTC, eomgerm commented on src/main/java/com/goormthonuniv/ownearth/service/MemberItemCommandService.java
이건 나중에 물건 구매할 때 사용하는 컨트롤러인가요?

2024-03-21 00:47 UTC, SIWON990327 commented on src/main/java/com/goormthonuniv/ownearth/service/MemberItemCommandService.java
오... 다른 브랜치에서 만든건데 왜 넘어왔지....

2024-03-21 00:51 UTC, SIWON990327 commented on src/main/java/com/goormthonuniv/ownearth/converter/ItemConverter.java
> +            .anyMatch(memberItem -> memberItem.getMember().getId().equals(member.getId()));
멤버 아이템에서 memberId와 입력받은 member의 id가 일치해야 구매한 아이템이라 생각했습니다!
아니면 자신이 구매한 아이템이 아니더라고 구매했다고 뜰 것 같아요

2024-03-21 00:53 UTC, eomgerm commented on src/main/java/com/goormthonuniv/ownearth/converter/ItemConverter.java
> +            .anyMatch(memberItem -> memberItem.getMember().getId().equals(member.getId()));
사용자가 들고있는 memberItem은 무조건 자신이 구매한 아이템만 뜨지 않나요?

2024-03-21 02:48 UTC, eomgerm approved these changes

2024-03-21 03:14 UTC, merged